services:
  compras:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: ${PORT}

      MONGODB_HOST: ${MONGODB_HOST}

      SUPABASE_PROJECT_URL: ${SUPABASE_PROJECT_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SERVICE_AUTH_EMAIL: ${SERVICE_AUTH_EMAIL}
      SERVICE_AUTH_PASSWORD: ${SERVICE_AUTH_PASSWORD}

      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}

      CONTENIDOS_SERVICE_BASE_URL: ${CONTENIDOS_SERVICE_BASE_URL}
      USUARIOS_SERVICE_BASE_URL: ${USUARIOS_SERVICE_BASE_URL}
      ESTADISTICAS_SERVICE_BASE_URL: ${ESTADISTICAS_SERVICE_BASE_URL}
      APP_BASE_URL: ${APP_BASE_URL}
    depends_on:
      - compras-mongodb
    profiles:
      - prod

  compras-mongodb:
    image: bitnami/mongodb:latest
    container_name: compras-mongodb
    restart: always
    environment:
      MONGODB_ROOT_USER: ${MONGODB_USERNAME}
      MONGODB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - compras-mongodb-data:/bitnami/mongodb

volumes:
  compras-mongodb-data:
